### ISSUE TITLE
respawn logic needs to be fixed

### ISSUE THREAD

**Issue by amiruqdah** [amiruqdah/mario-party#1]
Currently, we have spawning working but respawning is actually broken. Players should get killed an then spawn again immediately (if there are four players -maybe?) or a queue system can be used in order to pop/push players to spawn when larger groups are playing. :space_invader:

**Comment by amiruqdah** [comment]
Cranapple is already working on this [issue](https://github.com/amiruqdah/mario-party/tree/respawning)

**Comment by ltecot** [comment]
Works now. Some errors are given but doesn't seem to affect the game.
